// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3WZKBJaWuL_LLbV8brGeYpOmUDIrjLO8',
    appId: '1:540834339175:ios:aa5386359ef10fb8ab37c2',
    messagingSenderId: '540834339175',
    projectId: 'oreum-point',
    databaseURL: 'https://oreum-point.firebaseio.com',
    storageBucket: 'oreum-point.appspot.com',
    iosBundleId: 'kr.puze.coupon-market',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAjMlyiEcGhLCIh9SlBOmSaiPQKp7Y2FU',
    appId: '1:540834339175:android:d2c8e8dc4491d94aab37c2',
    messagingSenderId: '540834339175',
    projectId: 'oreum-point',
    databaseURL: 'https://oreum-point.firebaseio.com',
    storageBucket: 'oreum-point.appspot.com',
  );

}